### PR TITLE
fix GUID.to_string() and add Tests

### LINKED ISSUE #13: Minor bug in GUID.cpp
I wanted to write some tests and started with the `GUID` class.
That's where I found a bug in the `to_string()` method.

```
Test name: GUID to_string test
equality assertion failed
- Expected: {00000000-0000-0000-0000-000000000000}
- Actual  : {0-0-0-0-000}
```

The std::hex method does not seem to respect leading zeros.

I'll pull the tests with bug fix, when we are clear with the meson build system.

### PR DESCRIPTION
**Pull request by blu-base**
This PR includes a number of changes:

- add convenience functions, such as `operator==` ,and `operator!=` for GUIDs
- make the Data variables private, adding getters
- make `Data4` to `std::array` for convenience, return a std::array is more explicit than c-style array (imo)
- fix `to_string()` as indicated in #13
- make `from_string()` a bit more versatile by checking presence of separators(`{`,`-`,`} `)
- add a test suite for the GUID class

I used the GUID mostly as prototype to get more familiar with cppunit. In the test routines i used `tuple` as data collector... though i have the impression this is not very elegant.

### CODE REVIEW

File: src/lib/GUID.cpp [hunk 1]
```diff
@@ -23,13 +25,57 @@
 namespace libone
 {
 
+// {FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF}
+enum { MaxStringGUIDLength = 38};
+// FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
+enum { MinStringGUIDLength = 32};
```
Comment (tshikaboom) [inline src/lib/GUID.cpp]: These two enums look like they could be made private to the GUID class, as the only time they're used are in GUID::from_string() (you can look at the `static const` private members in FileNode.h for inspiration)

Could you also maybe make these to be of a stronger type? Seeing an `enum` seems kind of weird here (you can convince me otherwise)

File: src/lib/GUID.cpp [hunk 2]
```diff
@@ -70,20 +122,72 @@ bool GUID::is_equal(GUID other)
 }
 
 // This is used for FileDataStores. The GUID is given as a string in the file
-void GUID::from_string(std::string str)
+void GUID::from_string(std::string const str)
```
Comment (tshikaboom) [inline src/lib/GUID.cpp]: I actually wonder, seeing that you've made all these other constructors, might it be possible to rename this to `GUID::GUID(std::string const str)` while at it? :)

File: src/lib/GUID.cpp [hunk 3]
```diff
@@ -70,20 +122,72 @@ bool GUID::is_equal(GUID other)
...
 {
   ONE_DEBUG_MSG(("\n"));
```
Comment (tshikaboom) [inline src/lib/GUID.cpp]: nit: you can remove this debug log message if you want, it looks like it originated from code coming from ye olde ancient times

File: src/lib/GUID.cpp [hunk 4]
```diff
@@ -70,20 +122,72 @@ bool GUID::is_equal(GUID other)
...
+    return;
+  }
+
+  if (str.front() == '{' && str.size() > MaxStringGUIDLength)
+  {
+    return;
+  }
+
+
+  size_t i{0};
```
Comment (tshikaboom) [inline src/lib/GUID.cpp]: What is the meaning of `{0}` here? Does it make a difference somewhere later on?

File: src/lib/GUID.cpp [hunk 5]
```diff
@@ -70,20 +122,72 @@ bool GUID::is_equal(GUID other)
...
+  Data4[1] = strtol(str.substr(i,4).c_str(), NULL, 16);
+  i += 4;
+
+  Data4[2] = strtol(str.substr(i,4).c_str(), NULL, 16);
+  i += 4;
+
+  Data4[3] = strtol(str.substr(i,4).c_str(), NULL, 16);
+  i += 4;
 
   ONE_DEBUG_MSG((" from string, dat good?\n"));
```
Comment (tshikaboom) [inline src/lib/GUID.cpp]: nit: this can also be removed if you feel like it :)

File: src/lib/GUID.cpp [hunk 6]
```diff
@@ -70,20 +122,72 @@ bool GUID::is_equal(GUID other)
...
 
-  (void) str;
 }
+
+
+librevenge::RVNGInputStream *operator>>(librevenge::RVNGInputStream *input, GUID &obj)
```
Comment (tshikaboom) [inline src/lib/GUID.cpp:170]: I'm having trouble wrapping my head around this, could you show me an example on how to use this?

File: src/lib/libone_utils.cpp [hunk 7]
```diff
@@ -232,6 +234,30 @@ unsigned long getLength(const std::shared_ptr<librevenge::RVNGInputStream> input
...
 }
 
+template <typename T>
+std::string int_to_hex(const T i)
+{
+  std::stringstream stream;
+
+  stream << std::hex
+         << std::setfill('0')
+         << std::setw(sizeof(T)*2)
```
Comment (tshikaboom) [inline src/lib/libone_utils.cpp:244]: What does the `setw` do in this case? I understand it is to format the output string, but even when replacing `T` with one of the types below in my head, I'm having trouble :)

**Review by tshikaboom — COMMENTED** [review]
This is nice!

I've left a few comments mostly where I'm a bit confused (I guess I'm not that sharp in C++), otherwise this looks good. Also left some small improvement suggestions.

File: src/lib/GUID.cpp (hunk 1 above)
Comment (blu-base) [reply src/lib/GUID.cpp]: I see what your are meaning. I think i copied without much thought from Qt's Quuid class...
Will be fixed.

File: src/lib/GUID.cpp (hunk 2 above)
Comment (blu-base) [reply src/lib/GUID.cpp]: Sure, i'll make it a constructor. I needed these to conveniently prepare tests. This is the only place where i needed it.

I guess this could be made a debug only feature.

File: src/lib/GUID.cpp (hunk 3 above)
Comment (blu-base) [reply src/lib/GUID.cpp]: ok.

File: src/lib/GUID.cpp (hunk 5 above)
Comment (blu-base) [reply src/lib/GUID.cpp]: ok.

File: src/lib/GUID.cpp (hunk 6 above)
Comment (blu-base) [reply src/lib/GUID.cpp:170]: This piece overloads the `>>` operator. Defining it as a friend function and outside the class allows to write in a stream like fashion. Have a look at the example [`Header.cpp`](https://github.com/blu-base/libone/blob/guid_operator_overload/src/lib/Header.cpp), line 32ff. It makes parsing the guid class a tiny bit less verbose.

It's not really necessary. I wanted to see, whether you are open to this style of operator overloading.

File: src/lib/libone_utils.cpp (hunk 7 above)
Comment (blu-base) [reply src/lib/libone_utils.cpp:244]: `setw` sets the width of the output string. Predefining the width is necessary to refill the string with zeros if the hex number has leading zeros.
`std::hex` seems to neglect leading zeros.

File: src/lib/GUID.cpp (hunk 4 above)
Comment (blu-base) [reply src/lib/GUID.cpp]: The `0` is not necessary here. I'll make the initialization implicit.

File: src/lib/GUID.cpp (hunk 1 above)
Comment (tshikaboom) [reply src/lib/GUID.cpp]: After a brief search, I saw that single-member enums are used to get free-standing constants to work around older cpp compilers.. I guess Qt could be kind of in such a case, as it can sometimes target some unconventional architectures and compilers (embedded systems with years-old toolchains..). So I can see why they did it like that!

File: src/lib/GUID.cpp (hunk 6 above)
Comment (tshikaboom) [reply src/lib/GUID.cpp:170]: This actually seems really nice! I haven't done any operator overloading before and initially did this codebase coming more from a "pure C" point of view, so I'm all for using syntactic sugar whenever it makes sense (we're doing C++ after all).

File: src/lib/GUID.cpp (hunk 2 above)
Comment (blu-base) [reply src/lib/GUID.cpp]: Maybe making the extra constructors a test-only feature would be smarter.
Well for now, i just added a constructor which calls `from_string()`. Or do you want to get rid of it?

File: src/lib/GUID.cpp (hunk 1 above)
Comment (blu-base) [reply src/lib/GUID.cpp]: Thanks for sharing that information! This wasn't clear to me.

I replaced the enums anyway, since we can safely assume reasonably modern compilers.

File: src/lib/GUID.cpp (hunk 2 above)
Comment (tshikaboom) [reply src/lib/GUID.cpp]: I'd rather get rid of it because we don't have any users of `from_string()` at this point, so might as well. If that's not too much of a bother!

Let's leave the other constructors for now, as the created objects' contents are actually tested, so I guess that's proof enough that they work.

Comment (blu-base) [reply src/lib/GUID.cpp]: Ok, this feature is removed =)

Comment (tshikaboom) [reply src/lib/GUID.cpp]: Ohhh! No, sorry, I was just talking about moving method itself to a `GUID::GUID`(string) constructor, i.e. renaming it. I wasn't planning on nuking all this work you did!

Comment (blu-base) [reply src/lib/GUID.cpp]: Oh, haha, i didn't mind. I'll reset it.
In this context i noticed, i missed the most important test, the test for parsing the GUID from the byte stream.

**Comment by tshikaboom** [comment]
:+1: 
I'll wait for anything else you might want to add and will have a go at building and running this again this evening or tomorrow.

**Comment by blu-base** [comment]
Ok, . The parsing test wasn't really necessary, since we already compared OneNote's hard set GUID in the header.
But i think, it's good to propose a prototype for other tests.
